### PR TITLE
Preserve metadata in gzip_dir

### PR DESCRIPTION
**Pull request by shyamd**
Copy the metadata over to the gzip'ed file using shutil copystat

### CODE REVIEW

**Comment by shyamd** [comment]
Primary use case is custodian's gzip option to preserve the modification timestamp.

**Comment by shyuep** [comment]
Pls add unittest.

**Comment by shyamd** [comment]
Added in a Unit test and fixed some path resolution issues in gzip_dir

**Comment by shyuep** [comment]
TEsts failed. Think you need to do AlmostEqual.

**Comment by shyamd** [comment]
So it seems on Mac filestamps are resolved to the second level so assertEqual was working fine on my mac, but technically they can be resolved to less than a second, so AlmostEqual is the correct way. The nuances of modern computing...

**Comment by shyuep** [comment]
Note that you still have an issue with the text you read from the file. This seems that you were using python 2.7. I recommend that you move on to Py3. I will fix it this time.

**Pull request merged**
