### PR TITLE
Fix `MSONable.REDIRECT` when module name changed

### PR DESCRIPTION
**Pull request by janosh**
Only class name redirect was actually working. Fixed and now testing both cases.

## Summary by CodeRabbit

- **Refactor**
	- Improved class redirection handling in JSON processing.
- **Tests**
	- Enhanced tests for class redirection in JSON processing, including handling of `ImportError`.
- **Chores**
	- Updated linting workflow to use new `ruff` commands.
	- Updated repository revisions for pre-commit configurations.
- **Chores**
	- Added import statements for various modules in multiple files.
	- Added a docstring to `shutil.py`.

### CODE REVIEW

**Comment by janosh** [comment]
@DanielYang59 could you have a look at the test failures here?

```
FAILED tests/test_dev.py::TestDecorator::test_deprecated_deadline - DeprecationWarning: This function should have been removed on {deadline:%Y-%m-%d}.
FAILED tests/test_dev.py::TestDecorator::test_deprecated_deadline_no_warn - DeprecationWarning: This function should have been removed on {deadline:%Y-%m-%d}.
```

looks like there's a difference in behavior between running these tests locally vs in CI, probably from a difference in env vars (e.g. `GITHUB_REPOSITORY`)

**Comment by DanielYang59** [comment]
It's weird. I'm not seeing any test error for some reason? Is the test failing in your local env?

**Comment by janosh** [comment]
no, tests pass locally. i think part of the problem could be using `raise DeprecationWarning(...)`. warnings are not supposed to be raised but used like

```py
warnings.warn("This is a warning", category=DeprecationWarning)
```

**Comment by DanielYang59** [comment]
Oh... That's my mistake, I should have `warn` instead of `raise`. But either way, there should not be a `DeprecationWarning`.

I'm not seeing above mentioned warning anywhere (both locally and in CI), can you provide me a link?
```
FAILED tests/test_dev.py::TestDecorator::test_deprecated_deadline - DeprecationWarning: This function should have been removed on {deadline:%Y-%m-%d}.
FAILED tests/test_dev.py::TestDecorator::test_deprecated_deadline_no_warn - DeprecationWarning: This function should have been removed on {deadline:%Y-%m-%d}.
```

**Comment by janosh** [comment]
it was [only happening on my fork](https://github.com/janosh/monty/actions/runs/8489621426/job/23259919587) (didn't notice this before) so error must come from having a different `GITHUB_REPOSITORY`

**Comment by DanielYang59** [comment]
Ahh I see that now. I would create a branch in my fork and see if we could fix this. Sorry.

**Comment by janosh** [comment]
thanks! 👍

**Comment by DanielYang59** [comment]
I just [tried in my fork](https://github.com/DanielYang59/monty/actions/runs/8489891493) and everything seems to work just fine?

**Comment by janosh** [comment]
strange. i don't what's going on then

**Comment by DanielYang59** [comment]
Though the unit test is passing in my fork, there still is a undesired warning from one of the "no warn" cases, I would have a closer look tomorrow when I'm back to the office.
```
tests/test_dev.py::TestDecorator::test_deprecated_deadline
tests/test_dev.py::TestDecorator::test_deprecated_deadline_no_warn
  /Users/runner/work/monty/monty/monty/dev.py:79: DeprecationWarning: This function should have been removed on {deadline:%Y-%m-%d}.
    warnings.warn(
```

**Comment by DanielYang59** [comment]
> i think part of the problem could be using `raise DeprecationWarning(...)`. warnings are not supposed to be raised but used like

I think you're correct here. Only of the "no warn" cases issues an warning, as I was using the wrong syntax, it becomes an "error", and therefore the test failure. I would need to find out why the "no warn" case is warning.

**Comment by janosh** [comment]
@DanielYang59 thanks for investigating!

@shyuep this is ready to merge. the failing `codecov` CI is wrong, coverage increased with this PR

**Pull request merged**
