### PR TITLE
Allow binary in jsanitize for bson

### PR DESCRIPTION
**Pull request by shyamd**
Simple fix to allow binary data if allow_bson == True in jsanitize

### CODE REVIEW

**Comment by shyuep** [comment]
Pls fix the failing travis test.

**Comment by shyamd** [comment]
The test is failing in python2 because future doesn't seem to be installed . Do we want to scuttle py2 compatibility as a whole or add that into the requirements?

**Comment by shyuep** [comment]
Does the same functionality work in six? I have six?

**Comment by shyamd** [comment]
Had to remove the test for how python stringiness binary data. It's too fundamentally different in python2 and python3 without explicitly checking for version.

**Pull request merged**
