### PR TITLE
Bugfix: jsanitize crahses if pandas isn't installed (now fixed)

### PR DESCRIPTION
**Pull request by arosen93**
I forgot a parenthesis in #344 -- now fixed.

In practice, this causes a crash when running `jsanitize` for users without `pandas` installed due to a faulty boolean statement. It wasn't caught because `pandas` is installed during the CI testing.

### CODE REVIEW

**Comment by arosen93** [comment]
@shyuep: a head's up -- this is a minor bugfix. Tests pass.

**Comment by arosen93** [comment]
Also effects monty: https://github.com/materialsproject/maggma/pull/604

**Comment by arosen93** [comment]
@shyuep -- just wanted to ping you again about this one since it's an important patch. Thanks!

**Comment by shyuep** [comment]
Someone else already pushed a fix I think? Can you check? If it is not fixed, can you make sure the conflicts are resolved? Sorry about this.

**Comment by arosen93** [comment]
@shyuep, thanks for the heads up! I see @jmmshn got to it in https://github.com/materialsvirtuallab/monty/pull/365. I'll close this PR.

**Pull request closed without merging**
